### ISSUE TITLE
'%' returns NaN

### ISSUE THREAD

**Issue by simmax456** [simmax456/calculator#3]
I'm not sure why it's returning that.

**Comment by kontobaf** [comment]
You are most likely defining this function incorrectly.
try to implement it like this:
Set the number, then press multiply, enter the number and after entering the number press "%"

**Comment by kontobaf** [comment]
Since this function finds the percentage of a number
And how to set it as correctly as possible? Set the first number, then the second and already click on the function

**Comment by simmax456** [comment]
> You are most likely defining this function incorrectly. try to implement it like this: Set the number, then press multiply, enter the number and after entering the number press "%"

To make things simpler, I just straight up enter the number and once i click on "%", I want the result displayed

**Comment by simmax456** [comment]
Hi @kontobaf,
I've fixed the '%'. now i just need to fix my little bugs
